### ISSUE TITLE
Support rootless jailbreaks

### ISSUE THREAD

**Issue by cj81499** [cj81499/repo#9]
Rootless jailbreaks (eg: [Dopamine](https://ellekit.space/dopamine/)) are not supported. Add support.

Originally pointed out by @Thesius44 with #6.

**Comment by cj81499** [comment]
@Thesius44 I just published a new rootful and rootless version of `BarelyRounded`.

Can you confirm that it installs properly on your device?

If it does, it shouldn't be much work to apply the new process I developed for building packages to the other themes. Thanks!

**Comment by Thesius44** [comment]
Hey, I tested it and it works perfectly!  I can now see your repo and the barelyrounded theme.  You should be able to update everything else the same (hopefully cjglyphs!)

**Comment by cj81499** [comment]
@Thesius44 It took a few PRs, but I _think_ things ought to be updated and working for rootless. Try it out?
